# Generated by Django 3.0.5 on 2020-04-11 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('quote', models.CharField(default='Medicine is a science and an art.', max_length=272)),
                ('reference', models.URLField(help_text='Create google search like https://www.google.com/search?q= and add author and subject to find the quote and its context.')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
