# Generated by Django 3.0.5 on 2020-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('reference', models.URLField(help_text='Create google search like https://www.google.com/search?q= and add author and subject to find the quote and its context.')),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
