# Generated by Django 3.0.5 on 2020-04-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.CharField(default='Medicine is a science and an art.', max_length=272),
        ),
        migrations.AlterField(
            model_name='quote',
            name='year',
            field=models.IntegerField(),
        ),
    ]
